# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    environment: staging

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Replace values in .env.example
        env:
          APP_URL: ${{ secrets.APP_URL }}
          VAULT_URL: ${{ secrets.VAULT_URL }}
          VAULT_TOKEN: ${{ secrets.VAULT_TOKEN }}
          VAULT_VERSION: ${{ secrets.VAULT_VERSION }}
          VAULT_PATH: ${{ secrets.VAULT_PATH }}
          DOMAIN_REGISTRY: ${{ secrets.DOMAIN_REGISTRY }}
          USERNAME_REGISTRY: ${{ secrets.USERNAME_REGISTRY }}
          PASSWORD_REGISTRY: ${{ secrets.PASSWORD_REGISTRY }}
        run: |
          echo "APP_URL: $APP_URL"
          echo "VAULT_URL: $VAULT_URL"
          echo "VAULT_TOKEN: $VAULT_TOKEN"
          echo "VAULT_VERSION: $VAULT_VERSION"
          echo "VAULT_PATH: $VAULT_PATH"
          echo "DOMAIN_REGISTRY: $DOMAIN_REGISTRY"
          echo "USERNAME_REGISTRY: $USERNAME_REGISTRY"
          echo "PASSWORD_REGISTRY: $PASSWORD_REGISTRY"
